# Generated by Django 6.0.4 on 2026-06-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume_url',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
