# Generated by Django 6.0.4 on 2026-06-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_resume_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='resume_url',
            new_name='resume',
        ),
    ]
