# Generated by Django 6.0.4 on 2026-06-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_is_online_alter_userprofile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
