# Generated by Django 6.0.4 on 2026-07-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_userprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_connections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
