# Generated by Django 6.0.4 on 2026-05-21 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_PRIORITY_CHANGED', 'Task Priority Changed'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('TEAM_MEMBER_ADDED', 'Team Member Added'), ('TEAM_MEMBER_REMOVED', 'Team Member Removed')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='api.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_activities', to='api.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='activity_ac_team_id_36d01e_idx'), models.Index(fields=['task', '-created_at'], name='activity_ac_task_id_7a5790_idx'), models.Index(fields=['actor', '-created_at'], name='activity_ac_actor_i_200108_idx'), models.Index(fields=['activity_type'], name='activity_ac_activit_b6e897_idx')],
            },
        ),
    ]
