# Generated by Django 6.0.4 on 2026-05-21 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='activity_ac_activit_b6e897_idx',
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['team', 'activity_type', '-created_at'], name='activity_ac_team_id_e23bb4_idx'),
        ),
    ]
