# Generated by Django 6.0.4 on 2026-05-22 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_activity_activity_ac_activit_b6e897_idx_and_more'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_DELETED', 'Task Deleted'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_PRIORITY_CHANGED', 'Task Priority Changed'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('TASK_TITLE_CHANGED', 'Task Title Changed'), ('TASK_DUE_DATE_CHANGED', 'Task Due Date Changed'), ('TEAM_MEMBER_ADDED', 'Team Member Added'), ('TEAM_MEMBER_REMOVED', 'Team Member Removed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to='api.task'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_activities', to='api.team'),
        ),
    ]
