# Generated by Django 6.0.4 on 2026-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_alter_activity_activity_type_alter_activity_actor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("TASK_CREATED", "Task Created"),
                    ("TASK_DELETED", "Task Deleted"),
                    ("TASK_STATUS_CHANGED", "Task Status Changed"),
                    ("TASK_PRIORITY_CHANGED", "Task Priority Changed"),
                    ("TASK_ASSIGNED", "Task Assigned"),
                    ("TASK_UNASSIGNED", "Task Unassigned"),
                    ("TASK_TITLE_CHANGED", "Task Title Changed"),
                    ("TASK_DUE_DATE_CHANGED", "Task Due Date Changed"),
                    ("TEAM_NAME_CHANGED", "Team Name Changed"),
                    ("NEW_MEMBER_JOINED_TEAM", "New Member Joined Team"),
                    ("MEMBER_LEFT_TEAM", "Member Left Team"),
                    ("MEMBER_REMOVED_FROM_TEAM", "Member Removed From Team"),
                    ("MEMBER_PROMOTED_IN_TEAM", "Member Promoted in Team"),
                    ("MEMBER_DEMOTED_IN_TEAM", "Member Demoted in Team"),
                    ("TEAM_CREATED", "Team Created"),
                ],
                max_length=50,
            ),
        ),
    ]
