# Generated by Django 6.0.4 on 2026-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='team_chat_attachments/'),
        ),
    ]
