# Generated by Django 6.0.4 on 2026-06-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0003_alter_chats_sender_personalconversation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='attachments',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='personalmessage',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
