# Generated by Django 6.0.4 on 2026-06-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_created_by'),
        ('sockets', '0004_rename_attachments_chats_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalconversation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_conversations', to='api.team'),
        ),
    ]
