# Generated by Django 6.0.4 on 2026-06-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0005_personalconversation_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalconversation',
            name='team',
        ),
    ]
