# Generated by Django 6.0.4 on 2026-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('teamchat_new_attachment_uploaded', 'Teamchat New Attachment Uploaded')], max_length=50),
        ),
    ]
