# Generated by Django 6.0.4 on 2026-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('teamchat_new_attachment_uploaded', 'Teamchat New Attachment Uploaded'), ('team_member_joined', 'Team Member Joined'), ('team_member_left', 'Team Member Left'), ('team_member_removed', 'Team Member Removed')], max_length=50),
        ),
    ]
